baseURL = 'http://portfolio.adml.es/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'hugo-profile'

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Resume"
  url = "/resume"
  weight = 2

  [[menu.main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 3

  [[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 4

