baseURL = 'https://portfolio.adml.es/'
languageCode = 'en-us'
title = 'My Portfolio'
theme = 'hugo-profile'

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Resume"
  url = "/resume"
  weight = 2

  [[menu.main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 3

  [[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 4

[params]

  # Basic profile info
  name = "Adrian Melendez Lorenzo"
  subtitle = "AI Engineer"
  description = "Developer portfolio and blog built with Hugo"
  # Social links
  github = "https://github.com/AdrianMelendez"
  linkedin = "https://linkedin.com/in/adrian-melendez-lorenzo"

# Hero section config
  [params.hero]
    enable = true
    title = "Hi, I’m Adrian Melendez."
    subtitle = "I build modern websites and applications."
    showCVBtn = true
    cvBtnText = "Download CV"
    cvBtnURL = "/files/Adrian_Melendez_Resume.pdf"

  # Experience section (like demo)
  [params.experience]
    enable = true
    title = "Experience"
    subtitle = "A snapshot of my professional history"

    [[params.experience.items]]
      company = "Acme Corp"
      company_url = "https://acme.com"
      position = "Frontend Developer"
      duration = "Jan 2023 - Present"
      location = "Remote"
      content = "Built reusable React components and improved performance."

    [[params.experience.items]]
      company = "BetaTech"
      company_url = "https://betatech.io"
      position = "Software Engineer"
      duration = "Aug 2020 - Dec 2022"
      location = "San Francisco, CA"
      content = "Developed internal tools and automated testing pipelines."

  # Skills section
  [params.skills]
    enable = true
    title = "Skills"
    subtitle = "What I work with daily"

    [[params.skills.items]]
      name = "JavaScript"
      level = 90

    [[params.skills.items]]
      name = "Go"
      level = 75

    [[params.skills.items]]
      name = "Docker"
      level = 80

  # Projects section
  [params.projects]
    enable = true
    title = "Projects"
    subtitle = "Some things I’ve built"

    [[params.projects.items]]
      name = "Project One"
      url = "https://projectone.com"
      description = "A cool project using Hugo and Tailwind."

    [[params.projects.items]]
      name = "Project Two"
      url = "https://projecttwo.com"
      description = "An open-source tool for developers."

  # Footer and other options can go here
